### ISSUE TITLE
0415 '상자를 누르지 못했을 때' 조건 질문입니다! 

### ISSUE THREAD

**Issue by C7C4FF** [C7C4FF/start-fe#2]
https://github.com/C7C4FF/start-fe/blob/42a4dbc7e5923d7edbcb15599a419b440ae45ca9/06/quiz7.js#L25-L30
https://github.com/C7C4FF/start-fe/blob/42a4dbc7e5923d7edbcb15599a419b440ae45ca9/06/quiz7.js#L57-L62

@niceaji

2017108262 김희범입니다. 오늘 수업 중에 질문드렸던 내용입니다! 제가 이해하고 생각한 대로 쓰느라 틀린 부분이 있을 수 있습니다 ㅠㅠ

bug 함수가 setInterval 에 의해 3초 주기로 실행되고, 상자가 있든 없든 3초마다 새로운 상자가 나와서
한 상자를 그 주기 안에 누르지 못했을 때 생명을 차감하는 내용을 넣어봤습니다.

현재 방법으로도 작동은 잘 되지만, 만약 start 함수에서 라인 28과 29의 순서를 바꾼다면 (bug와 miss의 실행 순서를 바꾼다면) 코드 한 줄이라는 근소한 실행 시간 차이가 생길 것 같았습니다. 3초 주기의 마지막에 눌렀는데 누른 게 반영되지 못하고 그냥 점수가 깎이는 상황이 발생할 수도 있을 것 같아 순서를 바꿨지만, 왠지 임시방편인 것 같습니다.

발생할 확률이 극히 낮지만 (어쩌면 없을 수도 있겠습니다.) 이런 오류를 막기 위해서 저는 놓친 것을 확인하는 조건이 bug () 함수 안에서 처리되어야 한다고 생각했습니다. 이 bug 함수가 3초 주기로 동작하니 bug 함수가 3초 동안 유지된다고 생각했고, 그래서 그 함수의 마지막 시점(다시 함수가 호출되기 직전)에 확인하면 될 것 같았습니다.

근데 '함수의 마지막 시점'이라는 조건을 떠올리기는 쉬웠지만, 구현은 못했습니다 ㅠㅠ...

제가 생각해 본 방안은 이렇습니다.

1. 3초 주기로 실행되니 bug 함수 안에서 3초 후에 확인 조건이 실행되면 마지막 시점에 확인한다고 생각. bug 함수 마지막에 setTimeout으로 3초를 준 후 display 속성이 block 이냐 none 이냐를 파악.
-> 딱 한 번 동작하고 이후 동작하지 않았습니다. (제가 코딩을 잘못했을 수도 있습니다... ㅠㅠ)

2. 3초 동안 내내 조건을 확인함.
-> 구현이 가능한지도, 구현하는 방법도 모르겠습니다...

그래서 이 bug() 내에서 처리할 때 제가 생각한 방법을 구현할 수 있을지 궁금했습니다.

어떤 함수가 특정 시간동안 동작하니 조건을 검사하는 함수도 같은 시간 혹은 더 짧은 시간동안만 지속되는 조건을 줄 수 있는 방법이 있을까요?
혹은 함수가 다시 호출된다면 그 직전(마지막 시점)에 특정 조건을 처리하는 방법이 있을까요?

질문이 좀 난해한 것 같아서 죄송합니다 ㅠㅠ

**Comment by niceaji** [comment]
@C7C4FF 당장 읽어보기엔 양이 많네요. 
요약하면  추가하고싶은 기능이 '3초가 지나서 상자를 놓치면 생명 -1` 추가인거죠??

**Comment by C7C4FF** [comment]
@niceaji 네...!! bug 안에 넣는 경우는 그렇고, 질문을 좀 일반화 하면 > 조건을 검사하는 함수를 특정 시간동안만 지속되는 조건을 줄 수 있는 방법이 있을까요? < 입니다...! 천천히 답 주셔도 괜찮습니다! 항상 감사합니다!!

**Comment by niceaji** [comment]
@C7C4FF  
> 코드 한 줄이라는 근소한 실행 시간 차이가 생길 것 같았습니다
이러진 않아요. 어제 alert상황은 화면에 무언가 그려지거나 그럴경우엔 그럴수 있지만 코드상에선 당연히 위에부분이 먼저 실행됩니다 

>  조건을 검사하는 함수를 특정 시간동안만 지속되는 조건
이것도 말이 어렵긴하네요 ㅎ   함수를 특정시간동안만 지속하고 함수를 지우고 싶다는 얘기는 아닌거 같고

**Comment by niceaji** [comment]
@C7C4FF 함수의 마지막 시점이라는 표현도 재밌는데요.  지금처럼 miss()에서 구현하면 잘하신거 같은데요.
코드가 실행되는 타이밍등에서 좀더 복잡한 생각을 하고 계신것 같아요.  alert사건때문에 `순차적으로 흐르는 코드대로 실행된다` 라는걸 의심하게 된걸까요?

**Comment by niceaji** [comment]
@C7C4FF 
https://github.com/advanced-webapps-class/classroom/pull/30/files
'3초가 지나서 상자를 놓치면 생명 -1'  제가 추가해본 코드입니다.  참고하세요

**Comment by C7C4FF** [comment]
@niceaji 

답변 감사합니다! 결론부터 말씀드리면 해결됐습니다!

`조건을 검사하는 ~ 조건` 이 문장은 제가 다시 읽어봐도 읽히지 않네요.... 죄송합니다 ㅠㅠ
`QWERTY라는 함수 안에 if문을 QWERTY가 실행 된 10초부터 20초까지만 동작하게 만들 수 있나요` 였습니다.
 주신 답변도 보고, 생각을 정리해보니 제가 원하는 게 동영상 시작 후 5초 뒤에 동작하는 광고 스킵 버튼 같은 느낌인 것 같아서 직접 찾아보고 나중에 구현도 해보겠습니다 !

또 말씀해주신 것처럼 질문할 당시만 해도 코드가 한 줄, 한 줄 실행되니 (아주 낮은 확률이라도) 그 사이에 사용자의 입력이 들어오면 오류가 날 것 같았습니다. 제가 과할 만큼 복잡하게 생각하고 있었습니다.

생각을 정리하는 데 큰 도움이 되었습니다! 이 질문은 혹시 보실 분이 있으실까해서... 잠깐 열어뒀다가 닫겠습니다! 감사합니다!
